services:
  info-pg:
    container_name: info-pg
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    networks:
      - app-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=info

  info-app:
    container_name: info-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    networks:
      - app-network
    depends_on:
      - info-pg
    environment:
      - PORT=3333
      - POSTGRES_URL=postgresql://postgres:postgres@info-pg:5432/info?
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma db seed &&
        npm run dev
      "
    
networks:
  app-network:
    driver: bridge